// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CloseCashierModalController from "./close_cashier_modal_controller"
application.register("close-cashier-modal", CloseCashierModalController)

import ComboProductNormalPriceController from "./combo_product_normal_price_controller"
application.register("combo-product-normal-price", ComboProductNormalPriceController)

import ComboSelectController from "./combo_select_controller"
application.register("combo-select", ComboSelectController)

import CommissionRangeFormController from "./commission_range_form_controller"
application.register("commission-range-form", CommissionRangeFormController)

import CommissionRangeIndexController from "./commission_range_index_controller"
application.register("commission-range-index", CommissionRangeIndexController)

import CustomModalController from "./custom_modal_controller"
application.register("custom-modal", CustomModalController)

import CustomerFormController from "./customer_form_controller"
application.register("customer-form", CustomerFormController)

import CustomerTableModalController from "./customer_table_modal_controller"
application.register("customer-table-modal", CustomerTableModalController)

import DatatableController from "./datatable_controller"
application.register("datatable", DatatableController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import DynamicFormController from "./dynamic_form_controller"
application.register("dynamic-form", DynamicFormController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import Inventory__KardexController from "./inventory/kardex_controller"
application.register("inventory--kardex", Inventory__KardexController)

import Inventory__SelectWarehouseController from "./inventory/select_warehouse_controller"
application.register("inventory--select-warehouse", Inventory__SelectWarehouseController)

import InventoryController from "./inventory_controller"
application.register("inventory", InventoryController)

import InvoiceErrorModalController from "./invoice_error_modal_controller"
application.register("invoice-error-modal", InvoiceErrorModalController)

import InvoiceSeriesMappingController from "./invoice_series_mapping_controller"
application.register("invoice-series-mapping", InvoiceSeriesMappingController)

import LoaderController from "./loader_controller"
application.register("loader", LoaderController)

import MediaUploadController from "./media_upload_controller"
application.register("media-upload", MediaUploadController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import NavController from "./nav_controller"
application.register("nav", NavController)

import NestedFormController from "./nested_form_controller"
application.register("nested-form", NestedFormController)

import Dashboard__SelectLocationDropdownController from "./dashboard/select_location_dropdown_controller"
application.register("dashboard--select-location-dropdown", Dashboard__SelectLocationDropdownController)

import ObjectActionsDropdownController from "./object_actions_dropdown_controller"
application.register("object-actions-dropdown", ObjectActionsDropdownController)

import Pos__ButtonsController from "./pos/buttons_controller"
application.register("pos--buttons", Pos__ButtonsController)

import Pos__CommentModalController from "./pos/comment_modal_controller"
application.register("pos--comment-modal", Pos__CommentModalController)

import Pos__KeypadController from "./pos/keypad_controller"
application.register("pos--keypad", Pos__KeypadController)

import Pos__OrderItemsController from "./pos/order_items_controller"
application.register("pos--order-items", Pos__OrderItemsController)

import Pos__PaymentController from "./pos/payment_controller"
application.register("pos--payment", Pos__PaymentController)

import Pos__ProductGridController from "./pos/product_grid_controller"
application.register("pos--product-grid", Pos__ProductGridController)

import Pos__SellersModalController from "./pos/sellers_modal_controller"
application.register("pos--sellers-modal", Pos__SellersModalController)

import RequisitionFormController from "./requisition_form_controller"
application.register("requisition-form", RequisitionFormController)

import SelectController from "./select_controller"
application.register("select", SelectController)

import SellerBiweeklySalesTargetFormController from "./seller_biweekly_sales_target_form_controller"
application.register("seller-biweekly-sales-target-form", SellerBiweeklySalesTargetFormController)

import StockTransferFormController from "./stock_transfer_form_controller"
application.register("stock-transfer-form", StockTransferFormController)

import TabsController from "./tabs_controller"
application.register("tabs", TabsController)

import TooltipController from "./tooltip_controller"
application.register("tooltip", TooltipController)

import UppyUploadController from "./uppy_upload_controller"
application.register("uppy-upload", UppyUploadController)
