// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AttendanceFormController from "./attendance_form_controller"
application.register("attendance-form", AttendanceFormController)

import AttendanceLogsController from "./attendance_logs_controller"
application.register("attendance-logs", AttendanceLogsController)

import BulkTagController from "./bulk_tag_controller"
application.register("bulk-tag", BulkTagController)

import CalendarController from "./calendar_controller"
application.register("calendar", CalendarController)

import CloseCashierModalController from "./close_cashier_modal_controller"
application.register("close-cashier-modal", CloseCashierModalController)

import CollapsibleFieldController from "./collapsible_field_controller"
application.register("collapsible-field", CollapsibleFieldController)

import ComboProductNormalPriceController from "./combo_product_normal_price_controller"
application.register("combo-product-normal-price", ComboProductNormalPriceController)

import ComboSelectController from "./combo_select_controller"
application.register("combo-select", ComboSelectController)

import CommissionRangeFormController from "./commission_range_form_controller"
application.register("commission-range-form", CommissionRangeFormController)

import CustomModalController from "./custom_modal_controller"
application.register("custom-modal", CustomModalController)

import CustomerFormController from "./customer_form_controller"
application.register("customer-form", CustomerFormController)

import CustomerTableModalController from "./customer_table_modal_controller"
application.register("customer-table-modal", CustomerTableModalController)

import Dashboard__SelectLocationDropdownController from "./dashboard/select_location_dropdown_controller"
application.register("dashboard--select-location-dropdown", Dashboard__SelectLocationDropdownController)

import Dashboards__AutoRefreshController from "./dashboards/auto_refresh_controller"
application.register("dashboards--auto-refresh", Dashboards__AutoRefreshController)

import Dashboards__ChartsController from "./dashboards/charts_controller"
application.register("dashboards--charts", Dashboards__ChartsController)

import DatatableController from "./datatable_controller"
application.register("datatable", DatatableController)

import DatetimePickerController from "./datetime_picker_controller"
application.register("datetime-picker", DatetimePickerController)

import DiscountFormController from "./discount_form_controller"
application.register("discount-form", DiscountFormController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import DynamicFormController from "./dynamic_form_controller"
application.register("dynamic-form", DynamicFormController)

import DynamicProductFilterController from "./dynamic_product_filter_controller"
application.register("dynamic-product-filter", DynamicProductFilterController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import Inventory__KardexController from "./inventory/kardex_controller"
application.register("inventory--kardex", Inventory__KardexController)

import Inventory__SelectWarehouseController from "./inventory/select_warehouse_controller"
application.register("inventory--select-warehouse", Inventory__SelectWarehouseController)

import InventoryController from "./inventory_controller"
application.register("inventory", InventoryController)

import InvoiceErrorModalController from "./invoice_error_modal_controller"
application.register("invoice-error-modal", InvoiceErrorModalController)

import InvoiceSeriesMappingController from "./invoice_series_mapping_controller"
application.register("invoice-series-mapping", InvoiceSeriesMappingController)

import LoaderController from "./loader_controller"
application.register("loader", LoaderController)

import LocationSelectController from "./location_select_controller"
application.register("location-select", LocationSelectController)

import LoyaltyTierFormController from "./loyalty_tier_form_controller"
application.register("loyalty-tier-form", LoyaltyTierFormController)

import MediaUploadController from "./media_upload_controller"
application.register("media-upload", MediaUploadController)

import MinMaxStockController from "./min_max_stock_controller"
application.register("min-max-stock", MinMaxStockController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import NavController from "./nav_controller"
application.register("nav", NavController)

import NestedFormController from "./nested_form_controller"
application.register("nested-form", NestedFormController)

import ObjectActionsDropdownController from "./object_actions_dropdown_controller"
application.register("object-actions-dropdown", ObjectActionsDropdownController)

import OrderCommissionFormController from "./order_commission_form_controller"
application.register("order-commission-form", OrderCommissionFormController)

import OrderItemsController from "./order_items_controller"
application.register("order-items", OrderItemsController)

import OrderShowController from "./order_show_controller"
application.register("order-show", OrderShowController)

import PaymentEditorController from "./payment_editor_controller"
application.register("payment-editor", PaymentEditorController)

import PaymentFormController from "./payment_form_controller"
application.register("payment-form", PaymentFormController)

import Pos__BirthdayDiscountModalController from "./pos/birthday_discount_modal_controller"
application.register("pos--birthday-discount-modal", Pos__BirthdayDiscountModalController)

import Pos__ButtonsController from "./pos/buttons_controller"
application.register("pos--buttons", Pos__ButtonsController)

import Pos__CommentModalController from "./pos/comment_modal_controller"
application.register("pos--comment-modal", Pos__CommentModalController)

import Pos__KeypadController from "./pos/keypad_controller"
application.register("pos--keypad", Pos__KeypadController)

import Pos__LoyaltyInfoController from "./pos/loyalty_info_controller"
application.register("pos--loyalty-info", Pos__LoyaltyInfoController)

import Pos__OrderItemsController from "./pos/order_items_controller"
application.register("pos--order-items", Pos__OrderItemsController)

import Pos__PaymentController from "./pos/payment_controller"
application.register("pos--payment", Pos__PaymentController)

import Pos__PostPosSaleController from "./pos/post_pos_sale_controller"
application.register("pos--post-pos-sale", Pos__PostPosSaleController)

import Pos__ProductGridController from "./pos/product_grid_controller"
application.register("pos--product-grid", Pos__ProductGridController)

import Pos__SellersModalController from "./pos/sellers_modal_controller"
application.register("pos--sellers-modal", Pos__SellersModalController)

import ProductCategoryFormController from "./product_category_form_controller"
application.register("product-category-form", ProductCategoryFormController)

import ProductPackFormController from "./product_pack_form_controller"
application.register("product-pack-form", ProductPackFormController)

import ReportDateController from "./report_date_controller"
application.register("report-date", ReportDateController)

import RequisitionFormController from "./requisition_form_controller"
application.register("requisition-form", RequisitionFormController)

import SalesRankingController from "./sales_ranking_controller"
application.register("sales-ranking", SalesRankingController)

import SelectController from "./select_controller"
application.register("select", SelectController)

import SellerBiweeklySalesTargetFormController from "./seller_biweekly_sales_target_form_controller"
application.register("seller-biweekly-sales-target-form", SellerBiweeklySalesTargetFormController)

import StockTransferFormController from "./stock_transfer_form_controller"
application.register("stock-transfer-form", StockTransferFormController)

import StockTransferReceiveController from "./stock_transfer_receive_controller"
application.register("stock-transfer-receive", StockTransferReceiveController)

import TabsController from "./tabs_controller"
application.register("tabs", TabsController)

import TagFormController from "./tag_form_controller"
application.register("tag-form", TagFormController)

import TagTableModalController from "./tag_table_modal_controller"
application.register("tag-table-modal", TagTableModalController)

import TooltipController from "./tooltip_controller"
application.register("tooltip", TooltipController)

import UppyUploadController from "./uppy_upload_controller"
application.register("uppy-upload", UppyUploadController)

import WebcamController from "./webcam_controller"
application.register("webcam", WebcamController)
